POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "GetUserStorageNode",
  "query": "query GetUserStorageNode($nodePath: String!) { userStorageNode(nodePath: $nodePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "nodePath": "d1"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "GetUserStorageDirDescendants",
  "query": "query GetUserStorageDirDescendants($dirPath: String, $options: StoragePaginationOptionsInput) { userStorageDirDescendants(dirPath: $dirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "dirPath": "d1",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "GetUserStorageDescendants",
  "query": "query GetUserStorageDescendants($dirPath: String, $options: StoragePaginationOptionsInput) { userStorageDescendants(dirPath: $dirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "dirPath": "d1",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "GetUserStorageDirChildren",
  "query": "query GetUserStorageDirChildren($dirPath: String, $options: StoragePaginationOptionsInput) { userStorageDirChildren(dirPath: $dirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "dirPath": "d1",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "GetUserStorageChildren",
  "query": "query GetUserStorageChildren($dirPath: String, $options: StoragePaginationOptionsInput) { userStorageChildren(dirPath: $dirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "dirPath": "d1",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "GetUserStorageHierarchicalNodes",
  "query": "query GetUserStorageHierarchicalNodes($nodePath: String!) { userStorageHierarchicalNodes(nodePath: $nodePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "nodePath": "d1/d11/d111"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "GetUserStorageAncestorDirs",
  "query": "query GetUserStorageAncestorDirs($nodePath: String!) { userStorageAncestorDirs(nodePath: $nodePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "nodePath": "d1/d11/d111"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "HandleUploadedUserFile",
  "query": "mutation HandleUploadedUserFile($filePath: String!) { handleUploadedUserFile(filePath: $filePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "filePath": "d1/fileA.txt"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "CreateUserStorageDirs",
  "query": "mutation CreateUserStorageDirs($dirPaths: [String!]!) { createUserStorageDirs(dirPaths: $dirPaths) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "dirPaths": [
      "d1/d11",
      "d1/d11/d111",
      "d1/d11/d112",
      "dir2/dir2_1"
    ]
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "RemoveUserStorageDir",
  "query": "mutation RemoveUserStorageDir($dirPath: String!, $options: StoragePaginationOptionsInput) { removeUserStorageDir(dirPath: $dirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "dirPath": "d1",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "RemoveUserStorageFile",
  "query": "mutation RemoveUserStorageFile($filePath: String!) { removeUserStorageFile(filePath: $filePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "filePath": "d1/d11/fileA.txt"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "MoveUserStorageDir",
  "query": "mutation MoveUserStorageDir($fromDirPath: String!, $toDirPath: String!, $options: StoragePaginationOptionsInput) { moveUserStorageDir(fromDirPath: $fromDirPath, toDirPath: $toDirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "fromDirPath": "d1/d11",
    "toDirPath": "d1/d1X",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "MoveUserStorageFile",
  "query": "mutation MoveUserStorageFile($fromFilePath: String!, $toFilePath: String!) { moveUserStorageFile(fromFilePath: $fromFilePath, toFilePath: $toFilePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "fromFilePath": "d1/fileA.txt",
    "toFilePath": "d1/d11/fileA.txt"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "RenameUserStorageDir",
  "query": "mutation RenameUserStorageDir($dirPath: String!, $newName: String!, $options: StoragePaginationOptionsInput) { renameUserStorageDir(dirPath: $dirPath, newName: $newName, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "dirPath": "d1/d11",
    "newName": "d1X",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "RenameUserStorageFile",
  "query": "mutation RenameUserStorageFile($filePath: String!, $newName: String!) { renameUserStorageFile(filePath: $filePath, newName: $newName) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "filePath": "d1/fileA.txt",
    "newName": "fileB.txt"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "SetUserStorageDirShareSettings",
  "query": "mutation SetUserStorageDirShareSettings($dirPath: String!, $settings: StorageNodeShareSettingsInput!) { setUserStorageDirShareSettings(dirPath: $dirPath, settings: $settings) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "dirPath": "d1",
    "settings": { "isPublic": true, "readUIds": ["ichiro"], "writeUIds": ["ichiro"] }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user", "myDirName": "general.user"}

{
  "operationName": "SetUserStorageFileShareSettings",
  "query": "mutation SetUserStorageFileShareSettings($filePath: String!, $settings: StorageNodeShareSettingsInput!) { setUserStorageFileShareSettings(filePath: $filePath, settings: $settings) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "filePath": "d1/fileA.txt",
    "settings": { "isPublic": true, "readUIds": ["ichiro"], "writeUIds": ["ichiro"] }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "GetSignedUploadUrls",
  "query": "query GetSignedUploadUrls($inputs: [SignedUploadUrlInput!]!) { signedUploadUrls(inputs: $inputs) }",
  "variables": {
    "inputs": [
      {
        "filePath": "images/family.png",
        "contentType": "image/png"
      }
    ]
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "GetStorageNode",
  "query": "query GetStorageNode($nodePath: String!) { storageNode(nodePath: $nodePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "nodePath": "test-files/d1"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "GetStorageDirDescendants",
  "query": "query GetStorageDirDescendants($dirPath: String, $options: StoragePaginationOptionsInput) { storageDirDescendants(dirPath: $dirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "nodePath": "test-files/d1",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "GetStorageDescendants",
  "query": "query GetStorageDescendants($dirPath: String, $options: StoragePaginationOptionsInput) { storageDescendants(dirPath: $dirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "nodePath": "test-files/d1",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "GetStorageDirChildren",
  "query": "query GetStorageDirChildren($dirPath: String, $options: StoragePaginationOptionsInput) { storageDirChildren(dirPath: $dirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "nodePath": "test-files/d1",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "GetStorageChildren",
  "query": "query GetStorageChildren($dirPath: String, $options: StoragePaginationOptionsInput) { storageChildren(dirPath: $dirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "dirPath": "test-files/d1",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "GetStorageHierarchicalNodes",
  "query": "query GetStorageHierarchicalNodes($nodePath: String!) { storageHierarchicalNodes(nodePath: $nodePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "nodePath": "test-files/d1/d11/d111"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
"operationName": "GetStorageAncestorDirs",
"query": "query GetStorageAncestorDirs($nodePath: String!) { storageAncestorDirs(nodePath: $nodePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "nodePath": "test-files/d1/d11/d111"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "HandleUploadedFile",
  "query": "mutation HandleUploadedFile($filePath: String!) { handleUploadedFile(filePath: $filePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "filePath": "test-files/d1/fileA.txt"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "CreateStorageDirs",
  "query": "mutation CreateStorageDirs($dirPaths: [String!]!) { createStorageDirs(dirPaths: $dirPaths) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "dirPaths": [
      "test-files/d1/d11",
      "test-files/d1/d11/d111",
      "test-files/d1/d11/d112",
      "test-files/dir2/dir2_1"
    ]
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "RemoveStorageDir",
  "query": "mutation RemoveStorageDir($dirPath: String!, $options: StoragePaginationOptionsInput) { removeStorageDir(dirPath: $dirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "dirPath": "test-files/d1",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "RemoveStorageFile",
  "query": "mutation RemoveStorageFile($filePath: String!) { removeStorageFile(filePath: $filePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "filePath": "test-files/d1/fileA.txt"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "MoveStorageDir",
  "query": "mutation MoveStorageDir($fromDirPath: String!, $toDirPath: String!, $options: StoragePaginationOptionsInput) { moveStorageDir(fromDirPath: $fromDirPath, toDirPath: $toDirPath, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "fromDirPath": "test-files/d1/d11",
    "toDirPath": "test-files/d1/d1X",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "MoveStorageFile",
  "query": "mutation MoveStorageFile($fromFilePath: String!, $toFilePath: String!) { moveStorageFile(fromFilePath: $fromFilePath, toFilePath: $toFilePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "fromFilePath": "test-files/d1/fileA.txt",
    "toFilePath": "test-files/d1/d11/fileA.txt"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "RenameStorageDir",
  "query": "mutation RenameStorageDir($dirPath: String!, $newName: String!, $options: StoragePaginationOptionsInput) { renameStorageDir(dirPath: $dirPath, newName: $newName, options: $options) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } nextPageToken } }",
  "variables": {
    "dirPath": "test-files/d1/d11",
    "newName": "d1X",
    "options": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "RenameStorageFile",
  "query": "mutation RenameStorageFile($filePath: String!, $newName: String!) { renameStorageFile(filePath: $filePath, newName: $newName) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "filePath": "test-files/d1/fileA.txt",
    "newName": "fileB.txt"
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "SetStorageDirShareSettings",
  "query": "mutation SetStorageDirShareSettings($dirPath: String!, $settings: StorageNodeShareSettingsInput!) { setStorageDirShareSettings(dirPath: $dirPath, settings: $settings) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "dirPath": "test-files/d1",
    "settings": { "isPublic": true, "readUIds":  ["ichiro"], "writeUIds": ["ichiro"] }
  }
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin.user", "myDirName": "app.admin.user", "isAppAdmin": true}

{
  "operationName": "SetStorageFileShareSettings",
  "query": "mutation SetStorageFileShareSettings($filePath: String!, $settings: StorageNodeShareSettingsInput!) { setStorageFileShareSettings(filePath: $filePath, settings: $settings) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } created updated } }",
  "variables": {
    "filePath": "test-files/d1/fileA.txt",
    "settings": { "isPublic": true, "readUIds":  ["ichiro"], "writeUIds":  ["ichiro"] }
  }
}

###
