POST {{host}}/api/gql
Content-Type: application/json
Authorization: Bearer {"uid": "taro.yamada"}

{
  "operationName": "GetCartItems",
  "query": "query GetCartItems { cartItems { id uid productId title price quantity } }",
  "variables": {}
}

###

POST {{host}}/api/gql
Content-Type: application/json
Authorization: Bearer {"uid": "taro.yamada"}

{
  "operationName": "RemoveCartItems",
  "query": "mutation RemoveCartItems($ids: [ID!]!) { removeCartItems(ids: $ids) { id uid productId title price quantity } }",
  "variables": {
    "ids": [
      "cartItem1",
      "cartItem2"
    ]
  }
}
###

POST {{host}}/api/gql
Content-Type: application/json
Authorization: Bearer {"uid": "taro.yamada"}

{
  "operationName": "AddCartItems",
  "query": "mutation AddCartItems($inputs: [AddCartItemInput!]!) { addCartItems(inputs: $inputs) { id uid productId title price quantity product { id stock } } }",
  "variables": {
    "inputs": [
      {
        "productId": "product1",
        "title": "iPad 4 Mini",
        "price": 500.01,
        "quantity": 1
      },
      {
        "productId": "product2",
        "title": "Fire HD 8 Tablet",
        "price": 80.99,
        "quantity": 2
      }
    ]
  }
}

###

POST {{host}}/api/gql
Content-Type: application/json
Authorization: Bearer {"uid": "taro.yamada"}

{
  "operationName": "UpdateCartItems",
  "query": "mutation UpdateCartItems($inputs: [UpdateCartItemInput!]!) { updateCartItems(inputs: $inputs) { id uid productId title price quantity product { id stock } } }",
  "variables": {
    "inputs": [
      {
        "id": "cartItem1",
        "quantity": 1
      },
      {
        "id": "cartItem2",
        "quantity": 2
      }
    ]
  }
}

###

POST {{host}}/api/gql
Content-Type: application/json
Authorization: Bearer {"uid": "taro.yamada"}

{
  "operationName": "CheckoutCart",
  "query": "mutation CheckoutCart { checkoutCart }",
  "variables": {}
}

###
