POST {{apiHost}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "general"}

{
  "operationName": "GetAuthData",
  "query": "query GetAuthData { authData { status token user { id fullName email emailVerified isAppAdmin createdAt updatedAt publicProfile { id displayName photoURL createdAt updatedAt } } } }"
}

###

POST {{apiHost}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "test.storage"}

{
  "operationName": "DeleteOwnUser",
  "query": "mutation DeleteOwnUser { deleteOwnUser }"
}
