GET {{host}}/rest/keepalive
Authorization: Bearer {"uid": "app.admin", "isAppAdmin": true, "authStatus": "Available"}

###

GET {{host}}/storage/keepalive
Authorization: Bearer {"uid": "app.admin", "isAppAdmin": true, "authStatus": "Available"}

###
