POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageNode",
  "query": "query GetStorageNode($key: StorageNodeGetKeyInput!) { storageNode(key: $key) { id path } }",
  "variables": {
    "key": { "path": "test-files/d1" }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageNodes",
  "query": "query GetStorageNodes($key: StorageNodeGetKeysInput!) { storageNodes(key: $key) { id path } }",
  "variables": {
    "key": { "paths": ["test-files/d1"] }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageDescendants",
  "query": "query GetStorageDescendants($input: StorageNodeGetUnderInput!, $paging: PagingInput) { storageDescendants(input: $input, paging: $paging) { ... on PagingFirstResult { list { ... on StorageNode { id path } } token pageSegments pageSize pageNum totalPages totalItems, maxItems } ... on PagingAfterResult { list { ... on StorageNode { id path } } isPagingTimeout } } }",
  "variables": {
    "input": {
      "path": "test-files/d1",
      "includeBase": true
    },
    "paging": { "size": 3 }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageChildren",
  "query": "query GetStorageChildren($input: StorageNodeGetUnderInput!, $paging: PagingInput) { storageChildren(input: $input, paging: $paging) { ... on PagingFirstResult { list { ... on StorageNode { id path } } token pageSegments pageSize pageNum totalPages totalItems, maxItems } ... on PagingAfterResult { list { ... on StorageNode { id path } } isPagingTimeout } } }",
  "variables": {
    "input": {
      "path": "test-files/d1",
      "includeBase": true
    },
    "paging": { "size": 3 }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageHierarchicalNodes",
  "query": "query GetStorageHierarchicalNodes($nodePath: String!) { storageHierarchicalNodes(nodePath: $nodePath) { id path } }",
  "variables": {
    "nodePath": "test-files/d1/d11/d111"
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
"operationName": "GetStorageAncestorDirs",
"query": "query GetStorageAncestorDirs($nodePath: String!) { storageAncestorDirs(nodePath: $nodePath) { id path } }",
  "variables": {
    "nodePath": "test-files/d1/d11/d111"
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "CreateStorageDir",
  "query": "mutation CreateStorageDir($input: CreateStorageDirInput!) { createStorageDir(input: $input) { id path } }",
  "variables": {
    "input": {
      "dir": "test-files",
      "share": { "isPublic": true }
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "CreateStorageHierarchicalDirs",
  "query": "mutation CreateStorageHierarchicalDirs($dirs: [String!]!) { createStorageHierarchicalDirs(dirs: $dirs) { id path } }",
  "variables": {
    "dirs": [
      "test-files/d1/d11",
      "test-files/d1/d11/d111",
      "test-files/d1/d11/d112",
      "test-files/d2/d21"
    ]
  }
}

###

POST {{apiHost}}/gql_lv3
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RemoveStorageDir",
  "query": "mutation RemoveStorageDir($key: StorageNodeGetKeyInput!) { removeStorageDir(key: $key) }",
  "variables": {
    "key": {
      "path": "test-files/d1"
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RemoveStorageFile",
  "query": "mutation RemoveStorageFile($key: StorageNodeGetKeyInput!) { removeStorageFile(key: $key) { id path } }",
  "variables": {
    "key": {
      "path": "test-files/d1/fileA.txt"
    }
  }
}

###

POST {{apiHost}}/gql_lv3
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "MoveStorageDir",
  "query": "mutation MoveStorageDir($input: MoveStorageDirInput!) { moveStorageDir(input: $input) }",
  "variables": {
    "input": {
      "fromDir": "test-files/d1/d11",
      "toDir": "test-files/d1/d1X"
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "MoveStorageFile",
  "query": "mutation MoveStorageFile($fromFilePath: String!, $toFilePath: String!) { moveStorageFile(fromFilePath: $fromFilePath, toFilePath: $toFilePath) { id path } }",
  "variables": {
    "fromFilePath": "test-files/d1/fileA.txt",
    "toFilePath": "test-files/d1/d11/fileA.txt"
  }
}

###

POST {{apiHost}}/gql_lv3
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RenameStorageDir",
  "query": "mutation RenameStorageDir($input: RenameStorageDirInput!) { renameStorageDir(input: $input) }",
  "variables": {
    "input": {
      "dir": "test-files/d1/d11",
      "name": "d1X"
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RenameStorageFile",
  "query": "mutation RenameStorageFile($input: RenameStorageFileInput!) { renameStorageFile(input: $input) { id, path } }",
  "variables": {
    "input": {
      "file": "test-files/d1/fileA.txt",
      "name": "fileB.txt"
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "SetStorageDirShareDetail",
  "query": "mutation SetStorageDirShareDetail($key: StorageNodeGetKeyInput!, $input: StorageNodeShareDetailInput!) { setStorageDirShareDetail(key: $key, input: $input) { id path } }",
  "variables": {
    "key": { "path": "test-files/d1" },
    "input": { "isPublic": true, "readUIds":  ["ichiro"], "writeUIds": ["ichiro"] }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "SetStorageFileShareDetail",
  "query": "mutation SetStorageFileShareDetail($key: StorageNodeGetKeyInput!, $input: StorageNodeShareDetailInput!) { setStorageFileShareDetail(key: $key, input: $input) { id path } }",
  "variables": {
    "key": { "path": "test-files/d1/fileA.txt" },
    "input": { "isPublic": true, "readUIds":  ["ichiro"], "writeUIds":  ["ichiro"] }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "HandleUploadedFile",
  "query": "mutation HandleUploadedFile($input: StorageNodeKeyInput!) { handleUploadedFile(input: $input) { id path } }",
  "variables": {
    "input": {
      "id": "12345678901234567890",
      "path": "test-files/d1/fileA.txt"
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetSignedUploadUrls",
  "query": "query GetSignedUploadUrls($inputs: [SignedUploadUrlInput!]!) { signedUploadUrls(inputs: $inputs) }",
  "variables": {
    "inputs": [
      {
        "id": "12345678901234567890",
        "path": "images/family.png",
        "contentType": "image/png"
      }
    ]
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "CreateArticleTypeDir",
  "query": "mutation CreateArticleTypeDir($input: CreateArticleTypeDirInput!) { createArticleTypeDir(input: $input) { id path } }",
  "variables": {
    "input": {
      "lang": "ja",
      "dir": "",
      "label": "バンドル",
      "type": "ListBundle",
      "share": { "isPublic": true }
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "CreateArticleGeneralDir",
  "query": "mutation CreateArticleGeneralDir($input: CreateArticleGeneralDirInput!) { createArticleGeneralDir(input: $input) { id path } }",
  "variables": {
    "input": {
      "dir": "users/test.general/articles/assets/tmp",
      "share": { "isPublic": true }
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RenameArticleTypeDir",
  "query": "mutation RenameArticleTypeDir($input: RenameArticleTypeDirInput!) { renameArticleTypeDir(input: $input) { id } }",
  "variables": {
    "input": {
      "lang": "ja",
      "dir": "",
      "label": "バンドル"
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "SetArticleSortOrder",
  "query": "mutation SetArticleSortOrder($orderNodePaths: [String!]!) { setArticleSortOrder(orderNodePaths: $orderNodePaths) }",
  "variables": {
    "orderNodePaths": [
      "users/test.general/articles/12345678901234567890",
      "users/test.general/articles/abcdefghijklmnopqrst"
    ]
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "SaveArticleSrcContent",
  "query": "mutation SaveArticleSrcContent($key: StorageNodeGetKeyInput!, $input: SaveArticleSrcContentInput!) { saveArticleSrcContent(key: $key, input: $input) { id path } }",
  "variables": {
    "key": {
      "id": "12345678901234567890"
    },
    "input": {
      "lang": "ja",
      "srcContent": "test",
      "searchContent": "test"
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "SaveArticleDraftContent",
  "query": "mutation SaveArticleDraftContent($key: StorageNodeGetKeyInput!, $input: SaveArticleDraftContentInput!) { saveArticleDraftContent(key: $key, input: $input) { id path } }",
  "variables": {
    "key": {
      "id": "12345678901234567890"
    },
    "input": {
      "lang": "ja",
      "draftContent": "test"
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "test.general", "authStatus": "Available"}

{
  "operationName": "GetArticleContentsNode",
  "query": "query GetArticleContentsNode($key: StorageNodeGetKeyInput!, $input: GetArticleContentsNodeInput!) { articleContentsNode(key: $key, input: $input) { id path } }",
  "variables": {
    "key": { "id": "12345678901234567890" },
    "input": {
      "lang": "ja",
      "contentTypes": ["Src"]
    }
  }
}


###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetUserArticleList",
  "query": "query GetUserArticleList($input: GetUserArticleListInput!, $paging: PagingInput) { userArticleList(input: $input, paging: $paging) { ... on PagingFirstResult { list { ... on ArticleListItem { id label } } token pageSegments pageSize pageNum totalPages totalItems, maxItems } ... on PagingAfterResult { list { ... on ArticleListItem { id label } } isPagingTimeout } } }",
  "variables": {
    "input": {
      "lang": "ja",
      "articleDirId": "12345678901234567890"
    },
    "paging": { "size": 3 }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetUserArticleTableOfContents",
  "query": "query GetUserArticleTableOfContents($input: GetUserArticleTableOfContentsInput!) { userArticleTableOfContents(input: $input) { id path } }",
  "variables": {
    "input": {
      "lang": "ja",
      "userName": "test.general"
    }
  }
}

###

