POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageNode",
  "query": "query GetStorageNode($input: StorageNodeGetKeyInput!) { storageNode(input: $input) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } article { dir { name type sortOrder } src { type } } version createdAt updatedAt } }",
  "variables": {
    "input": { "path": "test-files/d1" }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageDirDescendants",
  "query": "query GetStorageDirDescendants($dirPath: String, $input: PaginationInput) { storageDirDescendants(dirPath: $dirPath, input: $input) { list { id path } nextPageToken } }",
  "variables": {
    "nodePath": "test-files/d1",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageDescendants",
  "query": "query GetStorageDescendants($dirPath: String, $input: PaginationInput) { storageDescendants(dirPath: $dirPath, input: $input) { list { id path } nextPageToken } }",
  "variables": {
    "nodePath": "test-files/d1",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageDirChildren",
  "query": "query GetStorageDirChildren($dirPath: String, $input: PaginationInput) { storageDirChildren(dirPath: $dirPath, input: $input) { list { id path } nextPageToken } }",
  "variables": {
    "nodePath": "test-files/d1",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageChildren",
  "query": "query GetStorageChildren($dirPath: String, $input: PaginationInput) { storageChildren(dirPath: $dirPath, input: $input) { list { id path } nextPageToken } }",
  "variables": {
    "dirPath": "test-files/d1",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageHierarchicalNodes",
  "query": "query GetStorageHierarchicalNodes($nodePath: String!) { storageHierarchicalNodes(nodePath: $nodePath) { id path } }",
  "variables": {
    "nodePath": "test-files/d1/d11/d111"
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
"operationName": "GetStorageAncestorDirs",
"query": "query GetStorageAncestorDirs($nodePath: String!) { storageAncestorDirs(nodePath: $nodePath) { id path } }",
  "variables": {
    "nodePath": "test-files/d1/d11/d111"
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "CreateStorageDir",
  "query": "mutation CreateStorageDir($dirPath: String!, $options: CreateStorageNodeOptions) { createStorageDir(dirPath: $dirPath, input: $input) { id path } }",
  "variables": {
    "dirPath": "test-files"
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "CreateStorageHierarchicalDirs",
  "query": "mutation CreateStorageHierarchicalDirs($dirPaths: [String!]!) { createStorageHierarchicalDirs(dirPaths: $dirPaths) { id path } }",
  "variables": {
    "dirPaths": [
      "test-files/d1/d11",
      "test-files/d1/d11/d111",
      "test-files/d1/d11/d112",
      "test-files/d2/d21"
    ]
  }
}

###

POST {{apiHost}}/gql_lv3
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RemoveStorageDir",
  "query": "mutation RemoveStorageDir($dirPath: String!) { removeStorageDir(dirPath: $dirPath) }",
  "variables": {
    "dirPath": "test-files/d1"
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RemoveStorageFile",
  "query": "mutation RemoveStorageFile($filePath: String!) { removeStorageFile(filePath: $filePath) { id path } }",
  "variables": {
    "filePath": "test-files/d1/fileA.txt"
  }
}

###

POST {{apiHost}}/gql_lv3
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "MoveStorageDir",
  "query": "mutation MoveStorageDir($fromDirPath: String!, $toDirPath: String!) { moveStorageDir(fromDirPath: $fromDirPath, toDirPath: $toDirPath) }",
  "variables": {
    "fromDirPath": "test-files/d1/d11",
    "toDirPath": "test-files/d1/d1X"
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "MoveStorageFile",
  "query": "mutation MoveStorageFile($fromFilePath: String!, $toFilePath: String!) { moveStorageFile(fromFilePath: $fromFilePath, toFilePath: $toFilePath) { id path } }",
  "variables": {
    "fromFilePath": "test-files/d1/fileA.txt",
    "toFilePath": "test-files/d1/d11/fileA.txt"
  }
}

###

POST {{apiHost}}/gql_lv3
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RenameStorageDir",
  "query": "mutation RenameStorageDir($dirPath: String!, $newName: String!) { renameStorageDir(dirPath: $dirPath, newName: $newName) }",
  "variables": {
    "dirPath": "test-files/d1/d11",
    "newName": "d1X"
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RenameStorageFile",
  "query": "mutation RenameStorageFile($filePath: String!, $newName: String!) { renameStorageFile(filePath: $filePath, newName: $newName) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "filePath": "test-files/d1/fileA.txt",
    "newName": "fileB.txt"
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "SetStorageDirShareDetail",
  "query": "mutation SetStorageDirShareDetail($key: StorageNodeGetKeyInput!, $input: SetShareDetailInput!) { setStorageDirShareDetail(key: $key, input: $input) { id path } }",
  "variables": {
    "key": { "path": "test-files/d1" },
    "input": { "isPublic": true, "readUIds":  ["ichiro"], "writeUIds": ["ichiro"] }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "SetStorageFileShareDetail",
  "query": "mutation SetStorageFileShareDetail($key: StorageNodeGetKeyInput!, $input: SetShareDetailInput!) { setStorageFileShareDetail(key: $key, input: $input) { id path } }",
  "variables": {
    "key": { "path": "test-files/d1/fileA.txt" },
    "input": { "isPublic": true, "readUIds":  ["ichiro"], "writeUIds":  ["ichiro"] }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "HandleUploadedFile",
  "query": "mutation HandleUploadedFile($input: StorageNodeKeyInput!) { handleUploadedFile(input: $input) { id path } }",
  "variables": {
    "input": {
      "id": "12345678901234567890",
      "path": "test-files/d1/fileA.txt"
    }
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetSignedUploadUrls",
  "query": "query GetSignedUploadUrls($inputs: [SignedUploadUrlInput!]!) { signedUploadUrls(inputs: $inputs) }",
  "variables": {
    "inputs": [
      {
        "id": "12345678901234567890",
        "path": "images/family.png",
        "contentType": "image/png"
      }
    ]
  }
}

###

POST {{apiHost}}/gql_lv1
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetArticleChildren",
  "query": "query GetArticleChildren($dirPath: String!, $types: [StorageArticleDirType!]!, $input: PaginationInput) { articleChildren(dirPath: $dirPath, types: $types, input: $input) { list { id path } nextPageToken } }",
  "variables": {
    "dirPath": "users/general/articles/blog",
    "types": "Article",
    "input": { "maxChunk": 3 }
  }
}

###
