POST {{apiHost}}/gql_standard
Content-Type: application/json

{
  "operationName": "GetAppConfig",
  "query": "query GetAppConfig { appConfig { storage { user { rootName } article { rootName fileName assetsName } } } }",
  "variables": {}
}

###
