POST {{host}}/gql
Content-Type: application/json

{
  "operationName": "GetAppConfig",
  "query": "query GetAppConfig { appConfig { user { rootName } article { rootName fileName assetsName } } }",
  "variables": {}
}

###
