POST {{apiHost}}/gql_example
Content-Type: application/json

{
  "operationName": "GetProducts",
  "query": "query GetProducts { products(ids: [\"product1\", \"product3\"]) { id title price stock version createdAt updatedAt } }",
  "variables": {}
}

###

POST {{apiHost}}/gql_example
Content-Type: application/json
Authorization: Bearer {"uid": "test.general", "authStatus": "Available"}

{
  "operationName": "GetCartItems",
  "query": "query GetCartItems($ids: [ID!]!) { cartItems(ids: $ids) { id uid productId title price quantity version createdAt updatedAt } }",
  "variables": {
    "ids": [
      "cartItem1",
      "cartItem2"
    ]
  }
}

###

POST {{apiHost}}/gql_example
Content-Type: application/json
Authorization: Bearer {"uid": "test.general", "authStatus": "Available"}

{
  "operationName": "AddCartItems",
  "query": "mutation AddCartItems($inputs: [CartItemAddInput!]!) { addCartItems(inputs: $inputs) { id uid productId title price quantity product { id title price stock version createdAt updatedAt } version createdAt updatedAt } }",
  "variables": {
    "inputs": [
      {
        "productId": "product1",
        "title": "iPad 4 Mini",
        "price": 500.01,
        "quantity": 1
      },
      {
        "productId": "product2",
        "title": "Fire HD 8 Tablet",
        "price": 80.99,
        "quantity": 2
      }
    ]
  }
}

###

POST {{apiHost}}/gql_example
Content-Type: application/json
Authorization: Bearer {"uid": "test.general", "authStatus": "Available"}

{
  "operationName": "UpdateCartItems",
  "query": "mutation UpdateCartItems($inputs: [CartItemUpdateInput!]!) { updateCartItems(inputs: $inputs) { id uid productId title price quantity product { id title price stock version createdAt updatedAt } version createdAt updatedAt } }",
  "variables": {
    "inputs": [
      {
        "id": "cartItem1",
        "quantity": 1
      },
      {
        "id": "cartItem2",
        "quantity": 2
      }
    ]
  }
}

###

POST {{apiHost}}/gql_example
Content-Type: application/json
Authorization: Bearer {"uid": "test.general", "authStatus": "Available"}

{
  "operationName": "RemoveCartItems",
  "query": "mutation RemoveCartItems($ids: [ID!]!) { removeCartItems(ids: $ids) { id uid productId title price quantity product { id title price stock version createdAt updatedAt } version createdAt updatedAt } }",
  "variables": {
    "ids": [
      "cartItem1",
      "cartItem2"
    ]
  }
}

###

POST {{apiHost}}/gql_example
Content-Type: application/json
Authorization: Bearer {"uid": "test.general", "authStatus": "Available"}

{
  "operationName": "CheckoutCart",
  "query": "mutation CheckoutCart { checkoutCart }",
  "variables": {}
}
