GET {{host}}/rest/cartItems
Authorization: Bearer {"uid": "general.user"}

###

GET {{host}}/rest/cartItems/cartItem1
Authorization: Bearer {"uid": "general.user"}

###

DELETE {{host}}/rest/cartItems
Content-Type: application/json
Authorization: Bearer {"uid": "general.user"}

[
  "cartItem1",
  "cartItem2"
]

###

POST {{host}}/rest/cartItems
Content-Type: application/json
Authorization: Bearer {"uid": "general.user"}

[
  {
    "productId": "product1",
    "title": "iPad 4 Mini",
    "price": 500.01,
    "quantity": 1
  },
  {
    "productId": "product2",
    "title": "Fire HD 8 Tablet",
    "price": 80.99,
    "quantity": 2
  }
]

###

PUT {{host}}/rest/cartItems
Content-Type: application/json
Authorization: Bearer {"uid": "general.user"}

[
  {
    "id": "cartItem1",
    "quantity": 1
  },
  {
    "id": "cartItem2",
    "quantity": 2
  }
]

###

PUT {{host}}/rest/cartItems/checkout
Content-Type: application/json
Authorization: Bearer {"uid": "general.user"}

###
