GET {{apiHost}}/rest/example/shop/products

###

GET {{apiHost}}/rest/example/shop/products?ids[]=product1&ids[]=product2

###

GET {{apiHost}}/rest/example/shop/cartItems
Authorization: Bearer {"uid": "general", "authStatus": "Available"}

###

GET {{apiHost}}/rest/example/shop/cartItems?ids[]=cartItem1&ids[]=cartItem2
Authorization: Bearer {"uid": "general", "authStatus": "Available"}

###

POST {{apiHost}}/rest/example/shop/cartItems
Content-Type: application/json
Authorization: Bearer {"uid": "general", "authStatus": "Available"}

[
  {
    "productId": "product1",
    "title": "iPad 4 Mini",
    "price": 500.01,
    "quantity": 1
  },
  {
    "productId": "product2",
    "title": "Fire HD 8 Tablet",
    "price": 80.99,
    "quantity": 2
  }
]

###

PUT {{apiHost}}/rest/example/shop/cartItems
Content-Type: application/json
Authorization: Bearer {"uid": "general", "authStatus": "Available"}

[
  {
    "id": "cartItem1",
    "quantity": 1
  },
  {
    "id": "cartItem2",
    "quantity": 2
  }
]

###

DELETE {{apiHost}}/rest/example/shop/cartItems?ids[]=cartItem1&ids[]=cartItem2
Content-Type: application/json
Authorization: Bearer {"uid": "general", "authStatus": "Available"}

###

PUT {{apiHost}}/rest/example/shop/checkoutCart
Content-Type: application/json
Authorization: Bearer {"uid": "general", "authStatus": "Available"}

###
