POST {{host}}/gql
Content-Type: application/json
#Origin: https://vue-base-project-7295.web.app

{
  "operationName": "GetProducts",
  "variables": {},
  "query": "query GetProducts { products(ids: [\"product1\", \"product3\"]) { id title price stock } }"
}

###
