### インデックス削除

DELETE {{elasticHost}}/example-suggest
Content-Type: application/json
Authorization: Basic {{elasticToken}}

### インデックス作成

# ■ icu_nfkc_normalizer
# 次のような変換を行ってくれる機能です。
#   ウ゛ェ → ヴェ
#   ＡＢＣ → ABC
#   ① → 1
#   ㊤ → 上
#   ㌶ → ヘクタール
#   ﾊﾝｶｸｶﾅ → ハンカクカナ

# ■ kana_to_romaji
# 仮名をローマ字に変換する機能です。

# ■ kuromoji_normal_tokenizer
# モードをnormalに設定して、単語を無駄に分割しすぎないようにします。
# ※「東京大学」はそのまま「東京大学」となります。

# ■ readingform
# 漢字をローマ字の読み仮名に変換する機能です。
# ※「寿司」は「sushi」に変換されます。

# ■ edge_ngram
# 指定した範囲の文字列を1文字ずつ分割します。
# ※ { "min_gram": 2, max_gram: 4 } と指定した場合、
#   「sushi」は「su、sus、sush」に分割されます。
#
# edge_ngramはngramと非常に似ていますが、edge_ngramはトークンの先頭から始まるn-gramのみを保持します。
#
# curl '…/_analyze?pretty=1&analyzer=my_ngram_analyzer' -d 'FC Schalke 04'
#   # FC, Sc, Sch, ch, cha, ha, hal, al, alk, lk, lke, ke, 04
#
# curl '…/_analyze?pretty=1&analyzer=my_edge_ngram_analyzer' -d 'FC Schalke 04'
#   # FC, Sc, Sch, Scha, Schal, 04

# ■ synonym
# 読み方が2種類以上ある単語を定義し吸収する機能です。
# ※「日本」は「nippon」または「nihon」と読むことがある。

PUT {{elasticHost}}/example-suggest
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "settings": {
    "analysis": {
      "char_filter": {
        "icu_nfkc_normalizer": {
          "type": "icu_normalizer",
          "name": "nfkc",
          "mode": "compose"
        },
        "kana_to_romaji": {
          "type": "mapping",
          "mappings": [
            "あ=>a",
            "い=>i",
            "う=>u",
            "え=>e",
            "お=>o",
            "か=>ka",
            "き=>ki",
            "く=>ku",
            "け=>ke",
            "こ=>ko",
            "さ=>sa",
            "し=>shi",
            "す=>su",
            "せ=>se",
            "そ=>so",
            "た=>ta",
            "ち=>chi",
            "つ=>tsu",
            "て=>te",
            "と=>to",
            "な=>na",
            "に=>ni",
            "ぬ=>nu",
            "ね=>ne",
            "の=>no",
            "は=>ha",
            "ひ=>hi",
            "ふ=>fu",
            "へ=>he",
            "ほ=>ho",
            "ま=>ma",
            "み=>mi",
            "む=>mu",
            "め=>me",
            "も=>mo",
            "や=>ya",
            "ゆ=>yu",
            "よ=>yo",
            "ら=>ra",
            "り=>ri",
            "る=>ru",
            "れ=>re",
            "ろ=>ro",
            "わ=>wa",
            "を=>o",
            "ん=>n",
            "が=>ga",
            "ぎ=>gi",
            "ぐ=>gu",
            "げ=>ge",
            "ご=>go",
            "ざ=>za",
            "じ=>ji",
            "ず=>zu",
            "ぜ=>ze",
            "ぞ=>zo",
            "だ=>da",
            "ぢ=>ji",
            "づ=>zu",
            "で=>de",
            "ど=>do",
            "ば=>ba",
            "び=>bi",
            "ぶ=>bu",
            "べ=>be",
            "ぼ=>bo",
            "ぱ=>pa",
            "ぴ=>pi",
            "ぷ=>pu",
            "ぺ=>pe",
            "ぽ=>po",
            "きゃ=>kya",
            "きゅ=>kyu",
            "きょ=>kyo",
            "しゃ=>sha",
            "しゅ=>shu",
            "しょ=>sho",
            "ちゃ=>cha",
            "ちゅ=>chu",
            "ちょ=>cho",
            "にゃ=>nya",
            "にゅ=>nyu",
            "にょ=>nyo",
            "ひゃ=>hya",
            "ひゅ=>hyu",
            "ひょ=>hyo",
            "みゃ=>mya",
            "みゅ=>myu",
            "みょ=>myo",
            "りゃ=>rya",
            "りゅ=>ryu",
            "りょ=>ryo",
            "ぎゃ=>gya",
            "ぎゅ=>gyu",
            "ぎょ=>gyo",
            "じゃ=>ja",
            "じゅ=>ju",
            "じょ=>jo",
            "びゃ=>bya",
            "びゅ=>byu",
            "びょ=>byo",
            "ぴゃ=>pya",
            "ぴゅ=>pyu",
            "ぴょ=>pyo",
            "ふぁ=>fa",
            "ふぃ=>fi",
            "ふぇ=>fe",
            "ふぉ=>fo",
            "ふゅ=>fyu",
            "うぃ=>wi",
            "うぇ=>we",
            "うぉ=>wo",
            "つぁ=>tsa",
            "つぃ=>tsi",
            "つぇ=>tse",
            "つぉ=>tso",
            "ちぇ=>che",
            "しぇ=>she",
            "じぇ=>je",
            "てぃ=>ti",
            "でぃ=>di",
            "でゅ=>du",
            "とぅ=>tu",
            "ぢゃ=>ja",
            "ぢゅ=>ju",
            "ぢょ=>jo",
            "ぁ=>a",
            "ぃ=>i",
            "ぅ=>u",
            "ぇ=>e",
            "ぉ=>o",
            "っ=>t",
            "ゃ=>ya",
            "ゅ=>yu",
            "ょ=>yo",
            "ア=>a",
            "イ=>i",
            "ウ=>u",
            "エ=>e",
            "オ=>o",
            "カ=>ka",
            "キ=>ki",
            "ク=>ku",
            "ケ=>ke",
            "コ=>ko",
            "サ=>sa",
            "シ=>shi",
            "ス=>su",
            "セ=>se",
            "ソ=>so",
            "タ=>ta",
            "チ=>chi",
            "ツ=>tsu",
            "テ=>te",
            "ト=>to",
            "ナ=>na",
            "ニ=>ni",
            "ヌ=>nu",
            "ネ=>ne",
            "ノ=>no",
            "ハ=>ha",
            "ヒ=>hi",
            "フ=>fu",
            "ヘ=>he",
            "ホ=>ho",
            "マ=>ma",
            "ミ=>mi",
            "ム=>mu",
            "メ=>me",
            "モ=>mo",
            "ヤ=>ya",
            "ユ=>yu",
            "ヨ=>yo",
            "ラ=>ra",
            "リ=>ri",
            "ル=>ru",
            "レ=>re",
            "ロ=>ro",
            "ワ=>wa",
            "ヲ=>o",
            "ン=>n",
            "ガ=>ga",
            "ギ=>gi",
            "グ=>gu",
            "ゲ=>ge",
            "ゴ=>go",
            "ザ=>za",
            "ジ=>ji",
            "ズ=>zu",
            "ゼ=>ze",
            "ゾ=>zo",
            "ダ=>da",
            "ヂ=>ji",
            "ヅ=>zu",
            "デ=>de",
            "ド=>do",
            "バ=>ba",
            "ビ=>bi",
            "ブ=>bu",
            "ベ=>be",
            "ボ=>bo",
            "パ=>pa",
            "ピ=>pi",
            "プ=>pu",
            "ペ=>pe",
            "ポ=>po",
            "キャ=>kya",
            "キュ=>kyu",
            "キョ=>kyo",
            "シャ=>sha",
            "シュ=>shu",
            "ショ=>sho",
            "チャ=>cha",
            "チュ=>chu",
            "チョ=>cho",
            "ニャ=>nya",
            "ニュ=>nyu",
            "ニョ=>nyo",
            "ヒャ=>hya",
            "ヒュ=>hyu",
            "ヒョ=>hyo",
            "ミャ=>mya",
            "ミュ=>myu",
            "ミョ=>myo",
            "リャ=>rya",
            "リュ=>ryu",
            "リョ=>ryo",
            "ギャ=>gya",
            "ギュ=>gyu",
            "ギョ=>gyo",
            "ジャ=>ja",
            "ジュ=>ju",
            "ジョ=>jo",
            "ビャ=>bya",
            "ビュ=>byu",
            "ビョ=>byo",
            "ピャ=>pya",
            "ピュ=>pyu",
            "ピョ=>pyo",
            "ファ=>fa",
            "フィ=>fi",
            "フェ=>fe",
            "フォ=>fo",
            "フュ=>fyu",
            "ウィ=>wi",
            "ウェ=>we",
            "ウォ=>wo",
            "ヴァ=>va",
            "ヴィ=>vi",
            "ヴ=>v",
            "ヴェ=>ve",
            "ヴォ=>vo",
            "ツァ=>tsa",
            "ツィ=>tsi",
            "ツェ=>tse",
            "ツォ=>tso",
            "チェ=>che",
            "シェ=>she",
            "ジェ=>je",
            "ティ=>ti",
            "ディ=>di",
            "デュ=>du",
            "トゥ=>tu",
            "ヂャ=>ja",
            "ヂュ=>ju",
            "ヂョ=>jo",
            "ァ=>a",
            "ィ=>i",
            "ゥ=>u",
            "ェ=>e",
            "ォ=>o",
            "ッ=>t",
            "ャ=>ya",
            "ュ=>yu",
            "ョ=>yo"
          ]
        }
      },
      "tokenizer": {
        "kuromoji_normal_tokenizer": {
          "mode": "normal",
          "type": "kuromoji_tokenizer"
        }
      },
      "filter": {
        "readingform": {
          "type": "kuromoji_readingform",
          "use_romaji": true
        },
        "edge_ngram": {
          "type": "edge_ngram",
          "min_gram": 1,
          "max_gram": 20
        },
        "synonym": {
          "type": "synonym",
          "lenient": true,
          "synonyms": ["nippon, nihon"]
        }
      },
      "analyzer": {
        "suggest_index_analyzer": {
          "type": "custom",
          "char_filter": ["icu_nfkc_normalizer"],
          "tokenizer": "kuromoji_normal_tokenizer",
          "filter": ["lowercase", "edge_ngram"]
        },
        "suggest_search_analyzer": {
          "type": "custom",
          "char_filter": ["icu_nfkc_normalizer"],
          "tokenizer": "kuromoji_normal_tokenizer",
          "filter": ["lowercase"]
        },
        "readingform_index_analyzer": {
          "type": "custom",
          "char_filter": ["icu_nfkc_normalizer", "kana_to_romaji"],
          "tokenizer": "kuromoji_normal_tokenizer",
          "filter": [ "lowercase", "readingform", "asciifolding", "synonym", "edge_ngram" ]
        },
        "readingform_search_analyzer": {
          "type": "custom",
          "char_filter": ["icu_nfkc_normalizer", "kana_to_romaji"],
          "tokenizer": "kuromoji_normal_tokenizer",
          "filter": ["lowercase", "readingform", "asciifolding", "synonym"]
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "my_field": {
        "type": "keyword",
        "fields": {
          "suggest": {
            "type": "text",
            "analyzer": "suggest_index_analyzer",
            "search_analyzer": "suggest_search_analyzer"
          },
          "readingform": {
            "type": "text",
            "analyzer": "readingform_index_analyzer",
            "search_analyzer": "readingform_search_analyzer"
          }
        }
      }
    }
  }
}

### テストデータ投入

# ※IntelliJでは実行できないためスニペットとして利用することを想定

POST /example-suggest/_bulk
{"index": {"_index": "example-suggest"}}
{"my_field": "日本", "created":"2016-11-11T11:11:11"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本", "created":"2017-11-11T11:11:11"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本", "created":"2018-11-11T11:11:11"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本", "created":"2019-11-11T11:11:11"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本", "created":"2020-11-11T11:11:11"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本", "created":"2020-11-11T11:11:11"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本 地図", "created":"2020-04-07T12:00:00"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本 地図", "created":"2020-03-11T12:00:00"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本 地図", "created":"2020-04-07T12:00:00"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本 地図", "created":"2020-04-07T12:00:00"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本 地図", "created":"2020-04-07T12:00:00"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本 郵便", "created":"2020-04-07T12:00:00"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本 郵便", "created":"2020-04-07T12:00:00"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本 郵便", "created":"2020-04-07T12:00:00"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本の人口", "created":"2020-04-07T12:00:00"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本の人口", "created":"2020-04-07T12:00:00"}
{"index": {"_index": "example-suggest"}}
{"my_field": "日本 代表", "created":"2020-04-07T12:00:00"}

### 検索クエリ

# ■ 検索ワードを以下のワードに差し替えて試してみること
#   「日本」「にほｎ」「にｈん」「にっほん」「日本ん」

# ■ 入力中の揺れが吸収される
# 例：検索キーワードとして「にｈん」と入力した場合に「日本」がサジェストされる
#
# インデックス時:
# - readingform_index_analyzer の結果、「日本」は「n、ni、nip、nipp、nippo、nippon、nih、niho、nihon」
#   に分割されます。
#
# 検索時:
# - readingform_search_analyzer では、char_filter の icu_nfkc_normalizer によって、全角の「にｈん」の
#   「ｈ」が半角の「h」に変換されます。
# - その後、char_filter の kana_to_romaji によって「にhん」が「nihn」に変換されます。 さらに一致クエリ
#   で「fuzziness: auto」を使用することにより、「nihn」が「nihon」に一致して期待されるサジェスト候補が
#   提示されます。

GET {{elasticHost}}/example-suggest/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "size": 0,
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "my_field.suggest": {
              "query": "にｈん"
            }
          }
        },
        {
          "match": {
            "my_field.readingform": {
              "query": "にｈん",
              "fuzziness":"auto",
              "operator": "and"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "keywords": {
      "terms": {
        "field": "my_field",
        "order": {
          "_count": "desc"
        },
        "size":"10"
      }
    }
  }
}

### suggest_search_analyzer の解析

GET {{elasticHost}}/example-suggest/_analyze
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "analyzer": "suggest_search_analyzer",
  "text": ["日本 地図"]
}

### readingform_index_analyzer の解析

GET {{elasticHost}}/example-suggest/_analyze
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "analyzer": "readingform_index_analyzer",
  "text": ["日本"]
}



