### インデックス削除

DELETE {{elasticHost}}/my-index-1
Content-Type: application/json
Authorization: Basic {{elasticToken}}

### インデックス作成

PUT {{elasticHost}}/my-index-1
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "settings": {
    "analysis": {
      "normalizer": {
        "keyword_lowercase": {
          "type": "custom",
          "filter": ["lowercase"]
        }
      },
      "filter": {
        "whitespace_remove": {
          "type": "pattern_replace",
          "pattern": "(\\s|　)",
          "replacement": ""
        }
      },
      "tokenizer": {
        "kuromoji_search_tokenizer": {
          "mode": "search",
          "type": "kuromoji_tokenizer"
        }
      },
      "analyzer": {
        "kuromoji_analyzer": {
          "type": "custom",
          "char_filter": [
            "kuromoji_iteration_mark"
          ],
          "tokenizer": "kuromoji_search_tokenizer",
          "filter": [
            "kuromoji_baseform",
            "kuromoji_part_of_speech",
            "kuromoji_stemmer",
            "kuromoji_number"
          ]
        },
        "kuromoji_html_analyzer": {
          "type": "custom",
          "char_filter": [
            "html_strip",
            "kuromoji_iteration_mark"
          ],
          "tokenizer": "kuromoji_search_tokenizer",
          "filter": [
            "kuromoji_baseform",
            "kuromoji_part_of_speech",
            "kuromoji_stemmer",
            "kuromoji_number"
          ]
        },
        "tags_index_analyzer": {
          "type": "custom",
          "tokenizer": "keyword",
          "filter": ["lowercase", "whitespace_remove"]
        },
        "tags_search_analyzer": {
          "type": "custom",
          "tokenizer": "whitespace",
          "filter": ["lowercase", "whitespace_remove"]
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "user_name": {
        "type": "text"
      },
      "date": {
        "type": "date"
      },
      "message": {
        "type": "text",
        "analyzer": "kuromoji_analyzer"
      },
      "tags": {
        "type": "text",
        "analyzer": "tags_index_analyzer",
        "search_analyzer": "tags_search_analyzer"
      }
    }
  }
}

### インデックスエイリアスの作成

POST {{elasticHost}}/_aliases
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "actions": [
    { "add": { "index": "my-index-1", "alias": "my-index" } }
  ]
}

### インデックスエイリアスの切り替え

POST {{elasticHost}}/_aliases
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "actions": [
    { "remove": { "index": "my-index-1", "alias": "my-index" } },
    { "add": { "index": "my-index-2", "alias": "my-index" } }
  ]
}

### 再インデックス

POST {{elasticHost}}/_reindex
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "source": { "index": "my-index-1" },
  "dest": { "index": "my-index-2" }
}

### 再インデックス処理の確認

GET {{elasticHost}}/_tasks?detailed=true&actions=*reindex
Content-Type: application/json
Authorization: Basic {{elasticToken}}

### 再インデックスのキャンセル

POST {{elasticHost}}/_tasks/{taskId}/_cancel
Content-Type: application/json
Authorization: Basic {{elasticToken}}

### インデックス設定を取得

GET {{elasticHost}}/my-index/_settings
Content-Type: application/json
Authorization: Basic {{elasticToken}}

### インデックス設定を更新

PUT {{elasticHost}}/my-index/_settings
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "index": {
    "max_result_window": 10000
  }
}

### テストデータ投入
# ※IntelliJでは実行できないためスニペットとして利用することを想定

POST /my-index/_bulk
{"index": {"_id": "1"}}
{"user_name": "坂本 清", "date": "2019-10-27T11:52:10", "message": "秋は京都で紅葉狩りをします。", "tags": ["俳優", "Designer"]}
{"index": {"_id": "2"}}
{"user_name": "冨永 愛", "date": "2019-10-27T11:52:10", "message": "私は奈良で紅葉狩りをしました。", "tags": ["俳優", "Super Model"]}
{"index": {"_id": "3"}}
{"user_name": "高野 人母美", "date": "2019-10-27T11:53:46", "message": "冬は北海道でスキーをします。", "tags": ["ボクサー", "Model"]}

### 全データ取得

GET {{elasticHost}}/my-index/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "match_all": {}
  },
  "_source": ["user_name", "date", "message", "tags"]
}

### データ追加・更新

PUT {{elasticHost}}/my-index/_doc/1
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "user_name": "坂本 清",
  "date": "2022-01-01T01:01:01",
  "message": "夏はオーストラリアで紅葉狩りをします。",
  "tags": ["俳優", "デザイナー"]
}

### 全文検索のサンプル

GET {{elasticHost}}/my-index/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "match": {
      "message": {
        "query": "紅葉狩り 京都",
        "operator": "and"
      }
    }
  },
  "highlight": {
    "fields": { "message": {} }
  }
}

### タグ検索のサンプル①
# データは頭文字が大文字だが、検索は大文字/小文字で検索可能

GET {{elasticHost}}/my-index/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "match": {
      "tags": "model"
    }
  }
}

### タグ検索のサンプル②
# OR検索

GET {{elasticHost}}/my-index/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "match": {
      "tags": {
        "query": "Designer ボクサー",
        "operator": "or"
      }
    }
  }
}

### タグ検索のサンプル③
# AND検索

GET {{elasticHost}}/my-index/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "match": {
      "tags": {
        "query": "俳優  　SuperModel　 ",
        "operator": "and"
      }
    }
  }
}

### kuromoji_analyzer の解析

GET {{elasticHost}}/my-index/_analyze
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "analyzer": "kuromoji_analyzer",
  "text": "秋は京都で紅葉狩りをします。"
}

### kuromoji_html_analyzer の解析

GET {{elasticHost}}/my-index/_analyze
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "analyzer": "kuromoji_html_analyzer",
  "text": "<p>私は<b>コンピューター</b>を持っています!</p>"
}

### tags_index_analyzer の解析

GET {{elasticHost}}/my-index/_analyze
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "analyzer": "tags_index_analyzer",
  "text": ["俳優", " 　Super　Model　 "]
}

### tags_search_analyzer の解析

GET {{elasticHost}}/my-index/_analyze
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "analyzer": "tags_search_analyzer",
  "text": "俳優  　SuperModel　 "
}
