# インデックスの削除

DELETE {{elasticHost}}/storage-nodes-test-1
Content-Type: application/json
Authorization: Basic {{elasticToken}}

###

# インデックスの作成

PUT {{elasticHost}}/storage-nodes-test-1
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "settings": {
    "analysis": {
      "analyzer": {
        "kuromoji_analyzer": {
          "type": "custom",
          "char_filter": [
            "kuromoji_iteration_mark"
          ],
          "tokenizer": "kuromoji_tokenizer",
          "filter": [
            "kuromoji_baseform",
            "kuromoji_part_of_speech",
            "kuromoji_stemmer",
            "kuromoji_number"
          ]
        },
        "kuromoji_html_analyzer": {
          "type": "custom",
          "char_filter": [
            "html_strip",
            "kuromoji_iteration_mark"
          ],
          "tokenizer": "kuromoji_tokenizer",
          "filter": [
            "kuromoji_baseform",
            "kuromoji_part_of_speech",
            "kuromoji_stemmer",
            "kuromoji_number"
          ]
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "id": {
        "type": "keyword"
      },
      "nodeType": {
        "type": "keyword"
      },
      "name": {
        "type": "keyword",
        "fields": {
          "text": {
            "type": "text",
            "analyzer": "kuromoji_analyzer"
          }
        }
      },
      "dir": {
        "type": "keyword",
        "fields": {
          "text": {
            "type": "text",
            "analyzer": "kuromoji_analyzer"
          }
        }
      },
      "path": {
        "type": "keyword",
        "fields": {
          "text": {
            "type": "text",
            "analyzer": "kuromoji_analyzer"
          }
        }
      },
      "contentType": {
        "type": "keyword"
      },
      "size": {
        "type": "float"
      },
      "share": {
        "properties": {
          "isPublic": {
            "type": "boolean"
          },
          "readUIds": {
            "type": "keyword"
          },
          "writeUIds": {
            "type": "keyword"
          }
        }
      },
      "article": {
        "properties": {
          "dir": {
            "properties": {
              "name": {
                "type": "keyword",
                "fields": {
                  "text": {
                    "type": "text",
                    "analyzer": "kuromoji_analyzer"
                  }
                }
              },
              "type": {
                "type": "keyword"
              },
              "sortOrder": {
                "type": "long"
              }
            }
          },
          "file": {
            "properties": {
              "type": {
                "type": "keyword"
              }
            }
          },
          "textContent": {
            "type": "text",
            "analyzer": "kuromoji_analyzer"
          }
        }
      },
      "level": {
        "type": "long"
      },
      "version": {
        "type": "long"
      },
      "createdAt": {
        "type": "date"
      },
      "updatedAt": {
        "type": "date"
      }
    }
  }
}

###

# インデックスエイリアスの作成

POST {{elasticHost}}/_aliases
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "actions": [
    { "add": { "index": "storage-nodes-test-1", "alias": "storage-nodes-test" } }
  ]
}

###

# インデックス情報の取得

GET {{elasticHost}}/storage-nodes-test
Content-Type: application/json
Authorization: Basic {{elasticToken}}

###

# 全ノード取得

GET {{elasticHost}}/storage-nodes-test/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "match_all": {}
  },
  "sort": [{ "path": "asc" }],
  "_source": ["id", "nodeType", "name", "dir", "path", "contentType", "size", "share.isPublic", "share.readUIds", "share.writeUIds", "article.dir.name", "article.dir.type", "article.dir.sortOrder", "article.file.type", "article.textContent", "version", "createdAt", "updatedAt"]
}

###

# ノードをキー(Id or パス)で検索

GET {{elasticHost}}/storage-nodes-test/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "bool": {
      "should": [
        { "term": { "id": "aAbBeEfFgGhHiIjJkKlL" } },
        { "term": { "path": "users/app.admin/articles/assets/pic2.jpg" } }
      ]
    }
  }
}

###

# ノードをキー(Id or パス)で複数検索

GET {{elasticHost}}/storage-nodes-test/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "bool": {
      "should": [
        { "terms": { "id": ["aAbBeEfFgGhHiIjJkKlL"] } },
        { "terms": { "path": ["users/app.admin/articles/assets/pic2.jpg"] } }
      ]
    }
  }
}

###

# 指定ディレクトリ配下のノードを検索

GET {{elasticHost}}/storage-nodes-test/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "wildcard": { "path": "users/app.admin/articles/*" }
  },
  "sort": [
    { "path": { "order": "asc" } }
  ],
  "_source": ["path"]
}

###

# 記事系ノードの検索

GET {{elasticHost}}/storage-nodes-test/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "exists": { "field": "articleNodeType" }
  }
}

###

# 公開設定されているノードを検索

GET {{elasticHost}}/storage-nodes/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "term": { "share.isPublic": true }
  },
  "sort": [
    { "path": { "order": "asc" } }
  ],
  "_source": ["path"]
}

###

# 指定ディレクトリで最大のソート順を取得

GET {{elasticHost}}/storage-nodes-test/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "size": 0,
  "query": {
    "term": {
      "dir": "users/app.admin/articles/aAbBeEfFgGhHiIjJkKlL"
    }
  },
  "aggs": {
    "max_order": {
      "max": {
        "field": "articleSortOrder"
      }
    }
  }
}

###

# 指定ディレクトリ配下にあるファイル数を取得

GET {{elasticHost}}/storage-nodes-test/_count
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "bool": {
      "must": [
        { "wildcard": { "path": "users/app.admin/*" } },
        { "term": { "nodeType": "File" } }
      ]
    }
  }
}

###

# 指定ディレクトリ配下にあるContent-Typeの種類を取得

GET {{elasticHost}}/storage-nodes-test/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "query": {
    "bool": {
      "must": [
        { "wildcard": { "path": "users/app.admin/*" } },
        {
          "bool": {
            "must_not": { "term": { "contentType": "" } }
          }
        }
      ]
    }
  },
  "collapse": {
    "field": "contentType"
  },
  "_source": ["contentType"]
}

###

# 指定ディレクトリ配下にあるContent-Typeの種類の数を取得

GET {{elasticHost}}/storage-nodes-test/_search
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "size": 0,
  "query": {
    "bool": {
      "must": [
        { "wildcard": { "path": "users/app.admin/*" } },
        {
          "bool": {
            "must_not": { "term": { "contentType": "" } }
          }
        }
      ]
    }
  },
  "aggs": {
    "contentTypeNum": {
      "cardinality": {
        "field": "contentType"
      }
    }
  }
}

###

# 記事テキストの更新

POST {{elasticHost}}/storage-nodes-test/_update/MSSufGqGSbot9j5wcUzE
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "doc": {
    "articleText": "僕の名前はヤンボー。ぼくの名前はマーボー。"
  }
}


###

# Analayzerの動作確認

POST {{elasticHost}}/_analyze
Content-Type: application/json
Authorization: Basic {{elasticToken}}

{
  "analyzer": "kuromoji",
  "text": "僕の名前はヤンボー。ぼくの名前はマーボー。"
}

###

# テストデータ投入
# ※IntelliJでは実行できないためスニペットとして利用することを想定

POST _bulk

{"index":{"_index":"storage-nodes-test","_id":"9eCIYveYOEeLmHoG9wiJ"}}
{"id":"9eCIYveYOEeLmHoG9wiJ","nodeType":"Dir","name":"users","dir":"","path":"users","level":1,"contentType":"","size":0,"share":{"readUIds":null,"isPublic":null,"writeUIds":null},"version":1,"createdAt":"2021-01-28 13:22:00","updatedAt":"2021-01-28 13:22:00"}
{"index":{"_index":"storage-nodes-test","_id":"MCsPXwH6sJgzaT3mqHcn"}}
{"id":"MCsPXwH6sJgzaT3mqHcn","nodeType":"Dir","name":"app.admin","dir":"users","path":"users/app.admin","level":2,"contentType":"","size":0,"share":{"readUIds":null,"isPublic":null,"writeUIds":null},"version":1,"createdAt":"2021-01-28 14:26:27","updatedAt":"2021-01-28 14:26:27"}
{"index":{"_index":"storage-nodes-test","_id":"xkoqcFH4B3edNPPCC4zR"}}
{"id":"xkoqcFH4B3edNPPCC4zR","nodeType":"Dir","name":"articles","dir":"users/app.admin","path":"users/app.admin/articles","level":3,"contentType":"","size":0,"share":{"readUIds":null,"isPublic":null,"writeUIds":null},"version":1,"createdAt":"2021-01-28 14:26:27","updatedAt":"2021-01-28 14:26:27"}
