POST {{host}}/api/gql
Content-Type: application/json

{
  "operationName": "GetAppConfig",
  "query": "query GetAppConfig { appConfig { usersDir } }",
  "variables": {}
}

###

POST {{host}}/api/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general.user"}

{
  "operationName": "GetCustomToken",
  "query": "query GetCustomToken { customToken }",
  "variables": {}
}

###
