POST {{host}}/api/gql
Content-Type: application/json
Authorization: Bearer {"uid": "yamada.one"}

{
  "operationName": "GetCustomToken",
  "query": "query GetCustomToken { customToken }",
  "variables": {}
}

###
