query GetUserStorageDirNodes {
  userStorageDirAndDescendants {
    nodeType
    name
    dir
    path
    created
    updated
  }
}
{ "authorization": "Bearer {\"uid\": \"general.user\"}" }

query GetUserStorageDirNodes {
  userStorageDirAndDescendants(dirPath: "dir1") {
    nodeType
    name
    dir
    path
    created
    updated
  }
}
{ "authorization": "Bearer {\"uid\": \"general.user\"}" }

query GetUserStorageDirNodes($dirPath: String) {
  userStorageDirAndDescendants(dirPath: $dirPath) {
    nodeType
    name
    dir
    path
    created
    updated
  }
}
{
  "dirPath": "dir1"
}
{ "authorization": "Bearer {\"uid\": \"general.user\"}" }

mutation CreateUserStorageDirs {
  createUserStorageDirs(dirPaths: ["dir1/dir1_1"]) {
    nodeType
    name
    dir
    path
    created
    updated
  }
}
{ "authorization": "Bearer {\"uid\": \"general.user\"}" }

mutation CreateUserStorageDirs($dirPaths: [String!]!) {
  createUserStorageDirs(dirPaths: $dirPaths) {
    nodeType
    name
    dir
    path
    created
    updated
  }
}
{
  "dirPaths": [
    "dir1/dir1_1",
    "dir1/dir1_1/dir1_1_1",
    "dir1/dir1_1/dir1_1_2",
    "dir2/dir2_1"
  ]
}
{ "authorization": "Bearer {\"uid\": \"general.user\"}" }

mutation RemoveUserStorageFileNodes {
  removeUserStorageFiles(filePaths: ["docs/fileA.txt"]) {
    nodeType
    name
    dir
    path
    created
    updated
  }
}
{ "authorization": "Bearer {\"uid\": \"general.user\"}" }

mutation RemoveUserStorageFileNodes($filePaths: [String!]!) {
  removeUserStorageFiles(filePaths: $filePaths) {
    nodeType
    name
    dir
    path
    created
    updated
  }
}
{
  "filePaths": ["docs/fileA.txt"]
}
{ "authorization": "Bearer {\"uid\": \"general.user\"}" }

mutation RemoveUserStorageDirNodes {
  removeUserStorageDir(dirPath: "dir1/dir1_1") {
    nodeType
    name
    dir
    path
    created
    updated
  }
}
{ "authorization": "Bearer {\"uid\": \"general.user\"}" }

mutation RemoveUserStorageDirNodes($dirPath: String!) {
  removeUserStorageDir(dirPath: $dirPath) {
    nodeType
    name
    dir
    path
    created
    updated
  }
}
{
  "dirPath": "dir1/dir1_1"
}
{ "authorization": "Bearer {\"uid\": \"general.user\"}" }

query GetSignedUploadUrls {
  signedUploadUrls(inputs: [
    { filePath: "images/family.png", contentType: "image/png" }
  ])
}
{ "authorization": "Bearer {\"uid\": \"app.admin.user\", \"isAppAdmin\": true}" }

query GetSignedUploadUrls($inputs: [SignedUploadUrlInput!]!) {
  signedUploadUrls(inputs: $inputs)
}
{
  "inputs": [
    {
      "filePath": "images/family.png",
      "contentType": "image/png"
    }
  ]
}
{ "authorization": "Bearer {\"uid\": \"app.admin.user\", \"isAppAdmin\": true}" }
