POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageNode",
  "query": "query GetStorageNode($nodePath: String!) { storageNode(nodePath: $nodePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "nodePath": "test-files/d1"
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageDirDescendants",
  "query": "query GetStorageDirDescendants($dirPath: String, $input: StoragePaginationInput) { storageDirDescendants(dirPath: $dirPath, input: $input) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } nextPageToken } }",
  "variables": {
    "nodePath": "test-files/d1",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageDescendants",
  "query": "query GetStorageDescendants($dirPath: String, $input: StoragePaginationInput) { storageDescendants(dirPath: $dirPath, input: $input) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } nextPageToken } }",
  "variables": {
    "nodePath": "test-files/d1",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageDirChildren",
  "query": "query GetStorageDirChildren($dirPath: String, $input: StoragePaginationInput) { storageDirChildren(dirPath: $dirPath, input: $input) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } nextPageToken } }",
  "variables": {
    "nodePath": "test-files/d1",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageChildren",
  "query": "query GetStorageChildren($dirPath: String, $input: StoragePaginationInput) { storageChildren(dirPath: $dirPath, input: $input) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } nextPageToken } }",
  "variables": {
    "dirPath": "test-files/d1",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetStorageHierarchicalNodes",
  "query": "query GetStorageHierarchicalNodes($nodePath: String!) { storageHierarchicalNodes(nodePath: $nodePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "nodePath": "test-files/d1/d11/d111"
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
"operationName": "GetStorageAncestorDirs",
"query": "query GetStorageAncestorDirs($nodePath: String!) { storageAncestorDirs(nodePath: $nodePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "nodePath": "test-files/d1/d11/d111"
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "CreateStorageDir",
  "query": "mutation CreateStorageDir($dirPath: String!, $input: CreateStorageNodeInput) { createStorageDir(dirPath: $dirPath, input: $input) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "dirPath": "test-files"
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "CreateStorageHierarchicalDirs",
  "query": "mutation CreateStorageHierarchicalDirs($dirPaths: [String!]!) { createStorageHierarchicalDirs(dirPaths: $dirPaths) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "dirPaths": [
      "test-files/d1/d11",
      "test-files/d1/d11/d111",
      "test-files/d1/d11/d112",
      "test-files/dir2/dir2_1"
    ]
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RemoveStorageDir",
  "query": "mutation RemoveStorageDir($dirPath: String!, $input: StoragePaginationInput) { removeStorageDir(dirPath: $dirPath, input: $input) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } nextPageToken } }",
  "variables": {
    "dirPath": "test-files/d1",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RemoveStorageFile",
  "query": "mutation RemoveStorageFile($filePath: String!) { removeStorageFile(filePath: $filePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "filePath": "test-files/d1/fileA.txt"
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "MoveStorageDir",
  "query": "mutation MoveStorageDir($fromDirPath: String!, $toDirPath: String!, $input: StoragePaginationInput) { moveStorageDir(fromDirPath: $fromDirPath, toDirPath: $toDirPath, input: $input) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } nextPageToken } }",
  "variables": {
    "fromDirPath": "test-files/d1/d11",
    "toDirPath": "test-files/d1/d1X",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "MoveStorageFile",
  "query": "mutation MoveStorageFile($fromFilePath: String!, $toFilePath: String!) { moveStorageFile(fromFilePath: $fromFilePath, toFilePath: $toFilePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "fromFilePath": "test-files/d1/fileA.txt",
    "toFilePath": "test-files/d1/d11/fileA.txt"
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RenameStorageDir",
  "query": "mutation RenameStorageDir($dirPath: String!, $newName: String!, $input: StoragePaginationInput) { renameStorageDir(dirPath: $dirPath, newName: $newName, input: $input) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } nextPageToken } }",
  "variables": {
    "dirPath": "test-files/d1/d11",
    "newName": "d1X",
    "input": { "maxChunk": 3 }
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "RenameStorageFile",
  "query": "mutation RenameStorageFile($filePath: String!, $newName: String!) { renameStorageFile(filePath: $filePath, newName: $newName) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "filePath": "test-files/d1/fileA.txt",
    "newName": "fileB.txt"
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "SetStorageDirShareSettings",
  "query": "mutation SetStorageDirShareSettings($dirPath: String!, $input: StorageNodeShareSettingsInput!) { setStorageDirShareSettings(dirPath: $dirPath, input: $input) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "dirPath": "test-files/d1",
    "input": { "isPublic": true, "readUIds":  ["ichiro"], "writeUIds": ["ichiro"] }
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "SetStorageFileShareSettings",
  "query": "mutation SetStorageFileShareSettings($filePath: String!, $input: StorageNodeShareSettingsInput!) { setStorageFileShareSettings(filePath: $filePath, input: $input) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "filePath": "test-files/d1/fileA.txt",
    "input": { "isPublic": true, "readUIds":  ["ichiro"], "writeUIds":  ["ichiro"] }
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "HandleUploadedFile",
  "query": "mutation HandleUploadedFile($filePath: String!) { handleUploadedFile(filePath: $filePath) { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } }",
  "variables": {
    "filePath": "test-files/d1/fileA.txt"
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetSignedUploadUrls",
  "query": "query GetSignedUploadUrls($inputs: [SignedUploadUrlInput!]!) { signedUploadUrls(inputs: $inputs) }",
  "variables": {
    "inputs": [
      {
        "filePath": "images/family.png",
        "contentType": "image/png"
      }
    ]
  }
}

###

POST {{host}}/gql_standard
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "authStatus": "Available", "isAppAdmin": true}

{
  "operationName": "GetArticleChildren",
  "query": "query GetArticleChildren($dirPath: String!, $articleTypes: [StorageArticleNodeType!]!, $input: StoragePaginationInput) { articleChildren(dirPath: $dirPath, articleTypes: $articleTypes, input: $input) { list { id nodeType name dir path contentType size share { isPublic readUIds writeUIds } articleNodeName articleNodeType articleSortOrder isArticleFile version createdAt updatedAt } nextPageToken } }",
  "variables": {
    "dirPath": "users/general/articles/blog",
    "articleTypes": "Article",
    "input": { "maxChunk": 3 }
  }
}

###
