POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "app.admin", "isAppAdmin": true, "authStatus": "Available"}

{
  "operationName": "KeepAlive",
  "query": "query KeepAlive { keepAlive }"
}

###

POST {{host}}/gql
Content-Type: application/json

{
  "operationName": "GetAppConfig",
  "query": "query GetAppConfig { appConfig { usersDir } }",
  "variables": {}
}

###

POST {{host}}/gql
Content-Type: application/json
Authorization: Bearer {"uid": "general"}

{
  "operationName": "GetCustomToken",
  "query": "query GetCustomToken { customToken }",
  "variables": {}
}

###
