POST {{host}}/gql
Content-Type: application/json

{
  "operationName": "GetAppConfig",
  "query": "query GetAppConfig { appConfig { users { dir } articles { dir assetsDir fileName } } }",
  "variables": {}
}

###
