GET {{host}}/rest/cartItems
Authorization: Bearer {"uid": "general"}

###

GET {{host}}/rest/cartItems?ids[]=cartItem1&ids[]=cartItem2
Authorization: Bearer {"uid": "general"}

###

POST {{host}}/rest/cartItems
Content-Type: application/json
Authorization: Bearer {"uid": "general"}

[
  {
    "productId": "product1",
    "title": "iPad 4 Mini",
    "price": 500.01,
    "quantity": 1
  },
  {
    "productId": "product2",
    "title": "Fire HD 8 Tablet",
    "price": 80.99,
    "quantity": 2
  }
]

###

PUT {{host}}/rest/cartItems
Content-Type: application/json
Authorization: Bearer {"uid": "general"}

[
  {
    "id": "cartItem1",
    "quantity": 1
  },
  {
    "id": "cartItem2",
    "quantity": 2
  }
]

###

DELETE {{host}}/cartItems?ids[]=cartItem1&ids[]=cartItem2
Content-Type: application/json
Authorization: Bearer {"uid": "general"}

###

PUT {{host}}/rest/cartItems/checkout
Content-Type: application/json
Authorization: Bearer {"uid": "general"}

###
