POST {{host}}/api/gql
Content-Type: application/json

{
  "operationName": "GetProducts",
  "variables": {},
  "query": "query GetProducts { products(ids: [\"product1\", \"product3\"]) { id title price stock } }"
}

###
